[build-system]
build-backend = 'mesonpy'
requires = ['meson-python']

[project]
name = 'genetic-algs'
version = '0.0.1'
description = 'Genetic algorithms'
readme = 'README.md'
requires-python = '>=3.9'