"""Describe sorting methods from _ga_operations extension."""
def bubble_sort(arr: list) -> list: ...
def select_sort(arr: list) -> list: ...
def sort(instances: list, method: str, *args, **kwargs) -> list: ...